[package]
name = "companion-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
companion-bridge = { path = "../companion-bridge", version = "0.1.0" }
companion-service = { path = "../companion-service", version = "0.1.0" }
tokio.workspace = true
tracing-subscriber.workspace = true
